import NissanGtr from '../images/Car/nissanGTR.png';
import Camaro from '../images/Car/Camaro.png';
import Honda from '../images/Car/HondaAccord.png';
import Hyundai from '../images/Car/Hyundai.png';
import Mazda from '../images/Car/Mazda.png';
import Porsche from '../images/Car/Porsche.png';
import Tesla from '../images/Car/Tesla.png';
import Toyota from '../images/Car/Toyota.png';

const carData = [
	{
		make: 'Honda',
		model: 'Accord',
		year: 2013,
		license: '6PWA542',
		color: 'White',
		numberOfSeats: 5,
		transmission: 'Automatic',
		engine: 'Petrol',
		vehicleClass: 'Sedan',
		image: Honda,
		priceId: 'price_1NHLgwKUpNsLneO9BuxTgoWK',
		price: 38.19,
	},
	{
		make: 'Tesla',
		model: 'Model S',
		year: 2017,
		license: '9DFA274',
		color: 'red',
		numberOfSeats: 5,
		transmission: 'Automatic',
		engine: 'Electric',
		vehicleClass: 'Sedan',
		image: Tesla,
		priceId: 'price_1NHLhEKUpNsLneO9ZfAVk7X4',
		price: 65.35,
	},
	{
		make: 'Nissan',
		model: 'GT-R NISMO',
		year: 2020,
		license: '7APW249',
		color: 'White',
		numberOfSeats: 4,
		transmission: 'Automatic',
		engine: 'Petrol',
		vehicleClass: 'Coupe',
		image: NissanGtr,
		priceId: 'price_1NHLgEKUpNsLneO9x1XzRtTh',
		price: 76.8,
	},
	{
		make: 'Porsche',
		model: 'Cayman',
		year: 2016,
		license: '3AXL904',
		color: 'Grey',
		numberOfSeats: 2,
		transmission: 'Manual',
		engine: 'Petrol',
		vehicleClass: 'Coupe',
		image: Porsche,
		priceId: 'price_1NHLhXKUpNsLneO9BJoLjJFQ',
		price: 102.9,
	},
	{
		make: 'Toyota',
		model: 'Sienna',
		year: 2021,
		license: '4LAD213',
		color: 'Grey',
		numberOfSeats: 8,
		transmission: 'Automatic',
		engine: 'Petrol',
		vehicleClass: 'Minivan',
		image: Toyota,
		priceId: 'price_1NHLi1KUpNsLneO9nVCMXwdw',
		price: 59.76,
	},
	{
		make: 'Chevrolet',
		model: 'Camaro',
		year: 2018,
		license: '5XRV384',
		color: 'Yellow',
		numberOfSeats: 4,
		transmission: 'Automatic',
		engine: 'Petrol',
		vehicleClass: 'Coupe',
		image: Camaro,
		priceId: 'price_1NHLigKUpNsLneO9QcIH8Kd2',
		price: 63.26,
	},
	{
		make: 'Hyundai',
		model: 'Ioniq 5',
		year: 2023,
		license: '6TRL932',
		color: 'Grey',
		numberOfSeats: 5,
		transmission: 'Automatic',
		engine: 'Electric',
		vehicleClass: 'SUV',
		image: Toyota,
		priceId: 'price_1NHLj7KUpNsLneO9HfiWseKL',
		price: 63.6,
	},
	{
		make: 'Mazda',
		model: '3',
		year: 2021,
		license: '8BPL323',
		color: 'White',
		numberOfSeats: 5,
		transmission: 'Automatic',
		engine: 'Petrol',
		vehicleClass: 'Sedan',
		image: Mazda,
		priceId: 'price_1NHLjPKUpNsLneO9gGTZZVGL',
		price: 42.1,
	},
];

export default carData;
